### ISSUE TITLE
macro c_rbnode_entry may avoid using unsigned long to cast pointer.

### ISSUE THREAD

**Issue by imzhuli** [c-util/c-rbtree#7]
// original code @ c-rbtree.h:147
#define c_rbnode_entry(_what, _t, _m) \
        ((_t *)(void *)(((unsigned long)(void *)(_what) ?: \
                         offsetof(_t, _m)) - offsetof(_t, _m)))

// i may say:
#define c_rbnode_entry(_what, _t, _m) \
        ((_t *)(void *)((_what) \
                ? ((unsigned char *)(_what) - offsetof(_t, _m)) \
                : NULL))

**Comment by dvdhrm** [comment]
Your suggestion breaks the tests, because it will evaluate "_what" twice. The original code carefully avoids this. This is one of the stupider parts of c macros... I should probably document it in the code.

**Comment by imzhuli** [comment]
My Bad.
Actually I did notice the 'avoiding calculating twice thing' when I read the codes at the first time, but I still wrote it  because I had not found a perfect way at that time, and I am so used to avoiding any side effects during macro uses, which could causes disasters in many 3rd party libs.

But my point is to avoid "pointer to unsigned long casting", because on MS platforms, unsigned long is 4 byte long, and is not large enough to hold pointer types.

Here are some other options:
1. using uintptr_t in stdint.h, unsigned integer type capable of holding a pointer to void, but uintptr_t is optional in C/C++ standard. So far as I know, it's so widely defined and I think is safe to use it.
2. using uintmax_t, which is not optional, may have some performance issues that uintmax_t might be larger than required size, and I believe compilers optimization is sure to overcome such minor things in most cases.  But I hate to say , years ago, some ms compiler options may cause uintmax_t too larger than standard integer types to support safe c++ pointer-to-member type casting.

A uintptr_t version is below, and meson test is passed:

#define c_rbnode_entry(_what, _t, _m) \
        ((_t *)(void *)(((uintptr_t)(void *)(_what) ?: \
                         (uintptr_t)offsetof(_t, _m)) - (uintptr_t)offsetof(_t, _m)))

**Comment by imzhuli** [comment]
Furthor more , 
1. stdint.h and stdbool.h should be included.
   including stdbool.h is for c++ compat
2. again, a c++ compat thing:  in c-rbtree.h link 170,   explicit cast from void * to CRBNode * is required. just like this:
    static inline CRBNode *c_rbnode_parent(CRBNode *n) {
        return (CRBNode *)((n->__parent_and_flags & C_RBNODE_ROOT) ?
                        NULL :
                        (void *)(n->__parent_and_flags & ~C_RBNODE_FLAG_MASK));
}

**Comment by dvdhrm** [comment]
This is now documented in the code-base. If anything is still unclear, please let me know! Thanks for the report!
