### ISSUE TITLE
use _Static_assert instead of static_assert may be more compatible

### ISSUE THREAD

**Issue by imzhuli** [c-util/c-rbtree#8]
I am writing something for some embeded devices, and the compiler is gcc 4.4. where macro static_assert is not included in assert.h
but using _Static_assert is fine.

**Comment by imzhuli** [comment]
there are 4 static_assert in c-rbtree.c

**Comment by dvdhrm** [comment]
gcc-4.4 was released 13 years ago, is there no way you can use a more recent release? It is weird to use a feature from the C11 standard, but only partly :-/

**Comment by imzhuli** [comment]
surely you are right and gcc-4.4 is just kind of die hard thing, and it's also weird to me too that some projects are still using that.
I just happened to crash into such things. sad.   :<

**Comment by dvdhrm** [comment]
I decided against doing that. The entire codebase of `c-util` (https://c-util.github.io) is targeted at ISO-C11, so I actually want to be able to use C11. Sure, changing small parts is not a big thing, but there is no guarantee that I will remember such oddities the next time we add static assertions. And it is just a maintenance burden to keep having to remember all this small things.

My recommendation is to keep local patches for gcc-4.4 compatibility, if necessary.

Sorry for declining the request, but I hope you can follow my argument.
